import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Bill, Settings } from "./types";
import { calculateBill, formatCurrency } from "./gst";

export function generateBillPDF(bill: Bill, settings: Settings): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const calc = calculateBill(bill.items, bill.gstType);

  // Header
  let y = 15;

  // Logo
  if (settings.logo) {
    try {
      doc.addImage(settings.logo, "JPEG", 15, y, 30, 30);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text(settings.shopName || "Shop", 50, y + 10);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      if (settings.shopAddress) {
        doc.text(settings.shopAddress, 50, y + 17);
      }
      if (settings.shopGSTIN) {
        doc.text(`GSTIN: ${settings.shopGSTIN}`, 50, y + 23);
      }
      y += 38;
    } catch {
      // invalid logo, skip
    }
  } else {
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(settings.shopName || "Shop", 15, y + 10);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    if (settings.shopAddress) {
      doc.text(settings.shopAddress, 15, y + 17);
    }
    if (settings.shopGSTIN) {
      doc.text(`GSTIN: ${settings.shopGSTIN}`, 15, y + 23);
    }
    y += settings.shopGSTIN ? 32 : settings.shopAddress ? 26 : 18;
  }

  // Divider
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(15, y, pageWidth - 15, y);
  y += 8;

  // BILL title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("TAX INVOICE", pageWidth / 2, y, { align: "center" });
  y += 8;

  // Bill info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Bill No: ${bill.id.slice(0, 8).toUpperCase()}`, 15, y);
  doc.text(`Date: ${new Date(bill.date).toLocaleDateString("en-IN")}`, pageWidth - 15, y, { align: "right" });
  y += 6;
  if (bill.customerName) {
    doc.text(`To: ${bill.customerName}`, 15, y);
    y += 5;
  }
  if (bill.customerPhone) {
    doc.text(`Phone: ${bill.customerPhone}`, 15, y);
    y += 5;
  }
  doc.text(`GST Type: ${bill.gstType === "intra" ? "Intra-State (CGST + SGST)" : "Inter-State (IGST)"}`, 15, y);
  y += 8;

  // Items table
  const gstHeader = bill.gstType === "intra"
    ? ["#", "Item", "HSN", "Qty", "Rate", "Amount", "CGST", "SGST", "Total"]
    : ["#", "Item", "HSN", "Qty", "Rate", "Amount", "IGST", "Total"];

  const tableData = bill.items.map((item, i) => {
    const c = calc.items[i];
    if (bill.gstType === "intra") {
      return [
        String(i + 1),
        item.name,
        item.hsn || "-",
        String(item.quantity),
        formatCurrency(item.rate),
        formatCurrency(c.amount),
        formatCurrency(c.cgst),
        formatCurrency(c.sgst),
        formatCurrency(c.amount + c.gstAmount),
      ];
    }
    return [
      String(i + 1),
      item.name,
      item.hsn || "-",
      String(item.quantity),
      formatCurrency(item.rate),
      formatCurrency(c.amount),
      formatCurrency(c.igst),
      formatCurrency(c.amount + c.gstAmount),
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [gstHeader],
    body: tableData,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [30, 30, 30] },
    columnStyles: {
      0: { cellWidth: 8 },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;

  // Totals
  const totalsX = pageWidth - 70;
  doc.setFont("helvetica", "normal");
  doc.text("Subtotal:", totalsX, y);
  doc.text(formatCurrency(calc.totalBeforeTax), pageWidth - 15, y, { align: "right" });
  y += 5;

  if (bill.gstType === "intra") {
    doc.text("CGST:", totalsX, y);
    doc.text(formatCurrency(calc.totalGST / 2), pageWidth - 15, y, { align: "right" });
    y += 5;
    doc.text("SGST:", totalsX, y);
    doc.text(formatCurrency(calc.totalGST / 2), pageWidth - 15, y, { align: "right" });
  } else {
    doc.text("IGST:", totalsX, y);
    doc.text(formatCurrency(calc.totalGST), pageWidth - 15, y, { align: "right" });
  }
  y += 6;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Grand Total:", totalsX, y);
  doc.text(formatCurrency(calc.grandTotal), pageWidth - 15, y, { align: "right" });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by BillBuddy", 15, footerY);
  doc.text("Signature", pageWidth - 15, footerY, { align: "right" });
  doc.line(pageWidth - 50, footerY - 1, pageWidth - 15, footerY - 1);

  return doc;
}

export function downloadPDF(bill: Bill, settings: Settings): void {
  const doc = generateBillPDF(bill, settings);
  doc.save(`bill-${bill.id.slice(0, 8)}.pdf`);
}

export function sharePDF(bill: Bill, settings: Settings): void {
  const doc = generateBillPDF(bill, settings);
  const blob = doc.output("blob");
  const file = new File([blob], `bill-${bill.id.slice(0, 8)}.pdf`, { type: "application/pdf" });

  if (navigator.share) {
    navigator.share({
      title: `Bill for ${bill.customerName || "Customer"}`,
      text: `Bill from ${settings.shopName} — Total: ₹${bill.grandTotal.toFixed(2)}`,
      files: [file],
    }).catch(() => {
      // fallback: just download
      downloadPDF(bill, settings);
    });
  } else {
    // fallback: WhatsApp
    const msg = encodeURIComponent(
      `Invoice from ${settings.shopName}\nTotal: ₹${bill.grandTotal.toFixed(2)}\nDate: ${new Date(bill.date).toLocaleDateString("en-IN")}`
    );
    window.open(`https://wa.me/?text=${msg}`, "_blank");
    downloadPDF(bill, settings);
  }
}